<?php
namespace calculadora;

/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface calculadoraIf
{
    /**
     * @param int $dividendo
     * @param int $divisor
     * @return double
     * @throws \calculadora\OperacionIvalida
     */
    public function division($dividendo, $divisor);
    /**
     * @param int $numero1
     * @param int $numero2
     * @return int
     * @throws \calculadora\OperacionIvalida
     */
    public function suma($numero1, $numero2);
    /**
     * @param int $numero1
     * @param int $numero2
     * @return int
     * @throws \calculadora\OperacionIvalida
     */
    public function multiplicacion($numero1, $numero2);
    /**
     * @param int $minuendo
     * @param int $sustraendo
     * @return int
     * @throws \calculadora\OperacionIvalida
     */
    public function resta($minuendo, $sustraendo);
}
